### ISSUE TITLE
Browser-sync blocks thread when scrolling

### ISSUE THREAD

**Issue by callumacrae** [BrowserSync/browser-sync-client#37]
Related: https://github.com/BrowserSync/browser-sync/issues/1203

browser-sync seems to phone home on every single scroll event, even when ghost mode is disabled. While this may seem like a useful feature for debugging scroll stuff on multiple devices at the same time, it actually does exactly the opposite: it blocks the thread for 5-10ms, lowering the FPS further on poorly performing apps (and making it super difficult to debug them!)

There seems to be no way to disable this, and so I can't use browser-sync when debugging scroll events.

<img width="703" alt="screen shot 2016-12-14 at 11 42 36" src="https://cloud.githubusercontent.com/assets/472830/21181072/042ac7a2-c1f4-11e6-9567-1e95e1bd5ce5.png">

Suggestions:

- [ ] When ghost mode is disabled, the event listener shouldn't be added
- [ ] Use [requestIdleCallback](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback) where available.
- [ ] When requestIdleCallback isn't available, either debounce / throttle the scroll events, or use an interval so that it doesn't fire as often as the scroll event does (a _lot_).

Happy to contribute code fixes if you're happy with the approach. I don't know how to do the first one, though.

**Comment by callumacrae** [comment]
With browser-sync:

<img width="588" alt="screen shot 2016-12-14 at 12 20 24" src="https://cloud.githubusercontent.com/assets/472830/21181847/c1e69516-c1f7-11e6-8a2c-79a716820236.png">

Without browser-sync:

<img width="613" alt="screen shot 2016-12-14 at 12 18 16" src="https://cloud.githubusercontent.com/assets/472830/21181849/c554b4da-c1f7-11e6-8e1c-11b207f69aa5.png">

**Comment by shakyShane** [comment]
@callumacrae Thanks for your investigations

>  When ghost mode is disabled, the event listener shouldn't be added

This was fixed in the last release

re: the second two point, I'm more than happy to get a PR for that. see https://github.com/BrowserSync/browser-sync-client/blob/master/lib/ghostmode.scroll.js

**Comment by callumacrae** [comment]
I'm running `browser-sync start --server --files "*" --no-ghost-mode` and browser-sync is still showing up in the timeline - am I disabling it correctly?
